ADMIN_databese/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from website.views import coming_soon
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^.*$', coming_soon),
    path('', include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path(r'', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from blog.views import *
app_name='blog'
urlpatterns = [
    path('', blog_view,name='index'),
    path('<int:pid>' ,blog_single,name='single'),
]

website/urls.py
from django.urls import path
from .views import *
app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
]

accounts/models.py
from django.db import models
# Create your models here.
class UserForm(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=100)
class ResetPasswordForm(models.Model):
    email = models.EmailField()

blog/models.py
from django.db import models
from django.contrib.auth.models import User 
class Post(models.Model):
    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    # tags = 
    # category = 
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
def __str__(self):
    return self.title

website/models.py
from django.db import models
class contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
def __str__(self):
    return self.name

accounts/forms.py
from django import forms
from accounts.models import UserForm
class UserForm(forms.ModelForm):
    class Meta:
        model = UserForm
        fields = '__all__'

website/forms.py
from django import forms
from website.models import contact
class Nameforms(forms.ModelForm):
    class Meta:
        model = contact
        fields = '__all__'
    def clean_name(self):
        return "Anonymous"
    subject = forms.CharField(required=False)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
import re
from accounts.forms import UserForm
from django.contrib.auth.forms import UserCreationForm

def login_view(request):
   error = None
   if request.method == 'POST':
       username_or_email = request.POST.get("username")
       password = request.POST.get("password")
       user = None

       # Check if the input is an email address
       if re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', username_or_email):
           try:
               user = User.objects.get(email=username_or_email)
               username = user.username
           except User.DoesNotExist:
               error = "User with this email does not exist"
       else:
           username = username_or_email

       if not error:
           user = authenticate(request, username=username, password=password)
           if user is not None:
               login(request, user)
               return redirect('/')
           else:
               error = 'نام کاربری یا رمز عبور اشتباه است'  
   form = AuthenticationForm()
   context = {'form': form, 'error': error}
   return render(request, 'accounts/login.html', context)
def signup_view(request):
   if request.user.is_authenticated:
       return redirect('/')
   if request.method == 'POST':
       form = UserForm(request.POST)
       if form.is_valid():
           data = form.cleaned_data
           username = data['username']
           email = data['email']
           password = data['password']
           confirm_password = request.POST.get('confirm')
           if not User.objects.filter(email=email).exists() and password == confirm_password:
               user = User.objects.create_user(username=username, password=password, email=email)
               user.save()
               return redirect('/accounts/login')
           else:
               error_message = 'User already exists or passwords do not match'
               return render(request, 'accounts/signup.html', {'form': form, 'error': error_message})
       else:
           error_message = 'Invalid form data'
           return render(request, 'accounts/signup.html', {'form': form, 'error': error_message})
   form = UserForm()
   return render(request, 'accounts/signup.html', {'form': form})

def logout_view(request):
   if request.user.is_authenticated:
       logout(request)
   return redirect('/')

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from blog.models import Post
from django.shortcuts import get_object_or_404
def blog_view(request):
    posts = Post.objects.filter(status=1, published_date__lte=timezone.now())
    context = {'posts':posts}
    return render(request,'blog/blog-home.html',context)
def blog_single(request, pid):
    post = get_object_or_404(Post, id=pid, status=1, published_date__lte=timezone.now())
    post.counted_views += 1
    post.save()
    previous_post = Post.objects.filter(published_date__lt=post.published_date, status=True).order_by('-published_date').first()
    next_post = Post.objects.filter(published_date__gt=post.published_date, status=True).order_by('published_date').first()
    context = {'post': post, 'previous_post': previous_post, 'next_post': next_post}
    return render(request, 'blog/blog-single.html', context)

website/views.py
from django.shortcuts import render
from website.forms import Nameforms
from django.contrib import messages
def index_view(request):
    return render(request, 'website\index.html')

def about_view(request):
    return render(request, 'website/about.html')

def contact_view(request):
    if request.method == 'POST':
        form = Nameforms(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS, 'successfull')
        else:
            messages.add_message(request,messages.ERROR,'ERROR')
    form = Nameforms()
    return render(request, 'website/contact.html',{'form':form})
def coming_soon(request):
    return render(request, 'coming_soon.html')

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Login</title>
   <style>
       .bg-image-vertical {
           position: relative;
           overflow: hidden;
           background-repeat: no-repeat;
           background-position: right center;
           background-size: auto 100%;
       }
       @media (min-width: 1025px) {
           .h-custom-2 {
               height: 100%;
           }
       }
       form {
           margin: auto;
           padding: auto;
       }
   </style>
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
   <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>
   <section class="vh-100">
       <div class="container-fluid">
           <div class="row">
               <div class="col-sm-6 text-black">
                   <div class="px-5 ms-xl-4">
                       <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                       <span class="h1 fw-bold mb-0" style="margin: auto; padding: auto;">Magical Travel</span>
                   </div>
                   <div class="d-flex align-items-center h-custom-1 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
                       <form style="width: 23rem;" method="post" action="{% url 'accounts:login' %}">
                           {% csrf_token %}
                           <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Log in</h3>
                           <div class="form-outline mb-4">
                               <input type="text" id="form2Example18" name="username" class="form-control form-control-lg" required />
                               <label class="form-label" for="form2Example18">Username or Email address</label>
                           </div>
                           <div class="form-outline mb-4">
                               <input type="password" id="form2Example28" name="password" class="form-control form-control-lg" required />
                               <label class="form-label" for="form2Example28">Password</label>
                           </div>
                           <div class="pt-1 mb-4">
                               <button class="btn btn-info btn-lg btn-block" type="submit">Login</button>
                           </div>
                           <p>Don't have an account? <a href="{% url 'accounts:signup' %}" class="link-info">Register here</a></p>
                           <p><a href="{% url 'accounts:password_reset' %}" class="link-info">Forgot Password</a></p>
                           {% if form.errors %}
                           <div class="form-group">
                               <div class="alert alert-danger" role="alert">
                                   {% for field in form %}
                                       {% for error in field.errors %}
                                           <p>{{ error }}</p>
                                       {% endfor %}
                                   {% endfor %}
                                   {% for error in form.non_field_errors %}
                                       <p>{{ error }}</p>
                                   {% endfor %}
                               </div>
                           </div>
                           {% else %}
                           {% if error %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <i class="fas fa-exclamation-circle"></i> {{ error }}
</div>
{% endif %}
                           {% endif %}
                       </form>
                   </div>
               </div>
               <div class="col-sm-6 px-0 d-none d-sm-block">
                   <img src="{% static 'img/20230119_114553.jpg' %}" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
               </div>
           </div>
       </div>
   </section>
</body>
</html>

templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <style>
        .bg-image-vertical {
            position: relative;
            overflow: hidden;
            background-repeat: no-repeat;
            background-position: right center;
            background-size: auto 100%;
        }

        @media (min-width: 1025px) {
            .h-custom-2 {
                height: 100%;
            }
        }
        form {
            margin: auto;
            padding: auto;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    <section class="vh-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">
                    <div class="px-5 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0" style="margin: auto; padding: auto;">Magical Travel</span>
                    </div>

                    <div class="d-flex align-items-center h-custom-1 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
                        <form style="width: 23rem;" method="post" action="{% url 'accounts:signup' %}">
                            {% csrf_token %}
                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Signup</h3>
                            <div class="form-outline mb-4">
                                <input type="text" class="form-control form-control-lg" name="username" required>
                                <label class="form-label">Username</label>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="email" id="form2Example18" class="form-control form-control-lg" name="email" required/>
                                <label class="form-label" for="form2Example18">Email address</label>
                            </div>

                            <div class="form-outline mb-4">
                                <input type="password" id="form2Example28" class="form-control form-control-lg" name="password" required/>
                                <label class="form-label" for="form2Example28">Password</label>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="password" id="form2Example28" class="form-control form-control-lg" name="confirm" required/>
                                <label class="form-label" for="form2Example28">Confirm Password</label>
                            </div>

                            <div class="pt-1 mb-4">
                                <button class="btn btn-info btn-lg btn-block" type="submit">Submit</button>
                            </div>
                            <p><a href="{% url 'accounts:login' %}" class="link-info">Login</a></p>
                        </form>
                    </div>
                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="{% static 'img/20230119_114553.jpg' %}" class="w-100 vh-100" style="object-fit: cover; object-position:left">
                </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/accounts/singup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <style>
        .bg-image-vertical {
            position: relative;
            overflow: hidden;
            background-repeat: no-repeat;
            background-position: right center;
            background-size: auto 100%;
        }

        @media (min-width: 1025px) {
            .h-custom-2 {
                height: 100%;
            }
        }
        form {
            margin: auto;
            padding: auto;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    <section class="vh-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">
                    <div class="px-5 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0" style="margin: auto; padding: auto;">Magical Travel</span>
                    </div>

                    <div class="d-flex align-items-center h-custom-1 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
                        <form style="width: 23rem;" method="post" action="{% url 'accounts:signup' %}">
                            {% csrf_token %}
                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Signup</h3>
                            <div class="form-outline mb-4">
                                <input type="text" class="form-control form-control-lg" name="username" required>
                                <label class="form-label">Username</label>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="email" id="form2Example18" class="form-control form-control-lg" name="email" required/>
                                <label class="form-label" for="form2Example18">Email address</label>
                            </div>

                            <div class="form-outline mb-4">
                                <input type="password" id="form2Example28" class="form-control form-control-lg" name="password" required/>
                                <label class="form-label" for="form2Example28">Password</label>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="password" id="form2Example28" class="form-control form-control-lg" name="confirm" required/>
                                <label class="form-label" for="form2Example28">Confirm Password</label>
                            </div>

                            <div class="pt-1 mb-4">
                                <button class="btn btn-info btn-lg btn-block" type="submit">Submit</button>
                            </div>
                            <p><a href="{% url 'accounts:login' %}" class="link-info">Login</a></p>
                        </form>
                    </div>
                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="{% static 'img/20230119_114553.jpg' %}" class="w-100 vh-100" style="object-fit: cover; object-position:left">
                </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/base.html
{% load compress %}
{% load static %}
	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Travel</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
		{% compress css %}
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href=" {% static 'css/linearicons.css' %}">
			<link rel="stylesheet" href=" {% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">				
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">							
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">				
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
		{% endcompress %}
		</head>
		<body>
    <!-- Modal for Messages -->
    <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		  <div class="modal-content">
			<div class="modal-header">
			  <h5 class="modal-title" id="messageModalLabel">Message</h5>
			  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			  </button>
			</div>
			<div class="modal-body">
			  <div id="modalMessageContent"></div>
			</div>
			<div class="modal-footer">
			  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		  </div>
		</div>
	  </div>
  
	  {% if messages %}
		<script>
		  document.addEventListener('DOMContentLoaded', function() {
			var modalMessageContent = document.getElementById('modalMessageContent');
			var messages = '';
			{% for message in messages %}
			  messages += '<div class="alert alert-{{ message.tags }}">{{ message }}</div>';
			{% endfor %}
			modalMessageContent.innerHTML = messages;
			$('#messageModal').modal('show');
		  });
		</script>
	  {% endif %}
			<header id="header">
				<div class="header-top">
					<div class="container">
			  		<div class="row align-items-center">
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
			  				<ul>
								{% if request.user.is_authenticated %}
								<li><a href="#">Logged in as {{request.user.username}}</a></li>
								<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
								{% else %}
								<li><a href="{% url 'accounts:login' %}">Login</a></li>
								<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
								{% endif %}
			  				</ul>			
			  			</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
			  		</div>			  					
					</div>
				</div>
				<div class="container main-menu">
					<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				        <a href="index.html"><img src="{%static 'img/logo.png' %}" alt="" title="" /></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li><a href="{% url 'website:index' %}">Home</a></li>
				          <li><a href="{% url 'website:about' %}">About</a></li>
				              <li><a href="{% url 'blog:index' %}">Blog</a></li>
				          <li class="menu-has-children"><a href="">Pages</a>
				            <ul>
				            	  <li><a href="elements.html">Elements</a></li>
						          <li class="menu-has-children"><a href="">Level 2 </a>
						            <ul>
						              <li><a href="#">Item One</a></li>
						              <li><a href="#">Item Two</a></li>
						            </ul>
						          </li>					                		
				            </ul>
				          </li>					          					          		          
				          <li><a href="{% url 'website:contact' %}">Contact</a></li>
				        </ul>
				      </nav><!-- #nav-menu-container -->					      		  
					</div>
				</div>
			</header><!-- #header -->
            {% block main %}
            
            {% endblock %}
            			<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">

					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point 
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="#">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="#">Blog</a></li>
											<li><a href="#">Contact</a></li>
										</ul>
									</div>										
								</div>							
							</div>
						</div>							
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.									
								</p>								
								<div id="mc_embed_signup">
									<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscription relative">
										<div class="input-group d-flex flex-row">
											<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>		
										</div>									
										<div class="mt-10 info"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
								</ul>
							</div>
						</div>						
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			{% compress js %}
            <script src="{% static 'js/vendor/jquery-2.2.4.min.js'%} "></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js'%}"></script>			
			<!-- <script src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA' %}"></script>		 -->
 			<script src="{% static 'js/jquery-ui.js'%}"></script>					
  			<script src="{% static 'js/easing.min.js'%}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>						
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>					
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>							
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>	
			{% endcompress %}
			<!-- End footer Area -->	
			 

templates/website/latest_posts.html
{% for post in posts %}
{% load static %}

<div class="single-recent-blog-post item">
    <div class="thumb">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{ post.title }}">
    </div>
    <div class="details">
        <div class="tags">
            <ul>
                {% for tag in post.tags.all %}
                    <li><a href="#">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <a href="{{ post.get_absolute_url }}"><h4 class="title">{{ post.title }}</h4></a>
        <p>{{ post.content|truncatechars:100 }}</p>
        <h6 class="date">{{ post.published_date }}</h6>
    </div>
</div>
{% endfor %}